# mysql-credentials-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials-secret # Nombre del secreto para las credenciales de MySQL
type: Opaque # Tipo de secreto opaco (uso general)
data:
  # ¡MUY IMPORTANTE! Reemplaza los valores con la codificación Base64 de tus credenciales REALES.
  # Puedes generar el valor Base64 en tu terminal de esta manera:
  # echo -n 'tu_contraseña_root' | base64
  # echo -n 'tu_contraseña_mysql' | base64
  # echo -n 'tu_usuario_mysql' | base64
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_PASSWORD: NDU3OA==
  MYSQL_USER: cmlreQ==

  # echo -n 'tu_client_id' | base64
  # echo -n 'tu_client_secret' | base64
  GOOGLE_CLIENT_ID: MjA1OTcwNDA2MTkzLWg4a24wcWNiNjhhNzJydTNsYXNxaWFkMXBlaWVpczgzLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t # Base64 de 'tu_client_id'
  GOOGLE_CLIENT_SECRET: R09DU1BYLUZfRXA0b2haMmNuZ2VTNTliRk02SGlXUEFCRlE= # Base64 de 'tu_client_secret'
