# phpmyadmin-deployment-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest # Imagen oficial de phpMyAdmin
          ports:
            - containerPort: 80 # Puerto por defecto de phpMyAdmin
          env:
            # Apunta phpMyAdmin al servicio de tu base de datos MySQL en Kubernetes
            - name: PMA_HOST
              value: zoo-app-mysql # Este es el nombre del servicio de tu MySQL (zoo-app-mysql)
            - name: PMA_PORT
              value: "3306" # Puerto de MySQL

            # Opcional: Configura phpMyAdmin para usar un usuario específico al inicio
            # Esto NO es para que la app se conecte, sino para el acceso inicial a phpMyAdmin.
            # Puedes usar tu usuario 'riky' o el 'root' si prefieres.
            # - name: PMA_USER
            #   value: riky
            # - name: PMA_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql-credentials-secret # Referencia a tu Secret de credenciales
            #       key: MYSQL_PASSWORD # La clave de la contraseña del usuario 'riky' o 'root'

          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"

---

# Servicio de phpMyAdmin - Expuesto vía NodePort

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  type: NodePort # Usamos NodePort para acceder desde fuera del clúster
  ports:
    - port: 80 # Puerto del servicio
      targetPort: 80 # Puerto del contenedor de phpMyAdmin
      nodePort: 30082 # Puerto en el nodo host (de 30000-32767). Asegúrate de que no esté en uso.
  selector:
    app: phpmyadmin # Selecciona los pods con la etiqueta 'app: phpmyadmin'
